### ISSUE TITLE
nodejs version

### ISSUE THREAD

**Issue by cr4zyfish** [Freddywhest/DropWizard#4]
why in setup nodejs 16 is installed but when running version 18 is required?

[install.sh](https://github.com/Freddywhest/DropWizard/blob/main/install.sh)
```
  # Install Node.js (This assumes a Debian-based system like Ubuntu)
  curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  sudo apt-get install -y nodejs
```

**Comment by Freddywhest** [comment]
This issue isn't related to this repository. You'll need to search online, as there are plenty of solutions available
