### ISSUE TITLE
Suggestions for new bots

### ISSUE THREAD

**Issue by Denver3D** [Freddywhest/DropWizard#6]
Dear Mr.Freddywhest

First I wanna thank you for your hard work on the script and I was wondering if it's possible to add the following Bots I believe they''ll have a bright future ? 
CryptoRank, YesCoin,PocketFi, MuskEmpire, HamsterKombat,OKX Racer, Nomis,Cats,MemeFi, CexIo

I saw someone made it for it (FaxWeb7) but it can't compare to your skills ❤️

**Comment by KVDcorp** [comment]
Agree, @Freddywhest , ur scripts too good. They work faster then other.
About new bots : [HEXN](https://t.me/hexn_bot/app?startapp=c46325fd-399c-47c4-91c8-5dd613b979a4), [CELL](https://t.me/cellCoin_bot/app?startapp=5911471051), [1win](http://t.me/token1win_bot/start?startapp=refId5911471051), [Xempire](https://t.me/empirebot/game?startapp=hero5911471051), [TapCoins](https://t.me/tapcoinsbot/app?startapp=ref_K7zNEB), [Altooshka](https://t.me/altooshka_bot?start=XktX7Qc_djA), [TimeTon](https://t.me/TimeTONbot?start=g69g96g),[ OrbitonX](https://t.me/orbitonx_bot/orbitonx?startapp=friendId5911471051), [Iceberg](https://t.me/IcebergAppBot?start=referral_5911471051), [Zavod](https://t.me/Mdaowalletbot?start=5911471051), [Mine2Mine](http://t.me/mine2mine_bot?start=gRpREn9g), [Solstone](https://t.me/solstonebot?start=5911471051) etc.

**Comment by Freddywhest** [comment]
PocketFi included already
