### ISSUE TITLE
DropWizard error

### ISSUE THREAD

**Issue by H4X0RA** [Freddywhest/DropWizard#8]
Rocket bunny stopped working? can you tell me what is wrong?
![Screenshot_5](https://github.com/user-attachments/assets/d5534ac0-8422-4ef1-9639-c85eb50bc88b)

**Comment by Hornak6** [comment]
Yes, same for me rockyrabbit is having issue
![dropwiz_error](https://github.com/user-attachments/assets/6e627490-381d-4af6-b48c-c461274e631c)

**Comment by Lastnet0709** [comment]
I also experienced it, turn it off for a while.
.env-general > ROCKYRABBIT=false

**Comment by Hornak6** [comment]
> I also experienced it, turn it off for a while. .env-general > ROCKYRABBIT=false

Well, let's try that. How long is this while?

**Comment by Freddywhest** [comment]
Fixed
